### PR TITLE
Validation fix for multiple char

### PR DESCRIPTION
**Pull request by Aniket21mathur**
The validation for num_page_entry box for only integer entries used to
validate for single characters given as input so when ever a string
starting with an integer is copied with Ctrl+V it is validated.For
eg "12ABCD".

Now checking for each char of the string before validating.

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
image
@quozl this is the same problem you pointed out in https://github.com/sugarlabs/convert/pull/21.

**Comment by Aniket21mathur** [comment]
@quozl I think you can review it better as you are already aware of the issue. :smile: Thanks!

**Comment by quozl** [comment]
Waiting on the other pull request to finish.

**Comment by Aniket21mathur** [comment]
Can we complete this pull request now :smile: ? Thanks!

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Pull request merged**
