### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by anmol27katyani**

### CODE REVIEW

**Comment by quozl** [comment]
@octamois, did you test this, and is this ready to be tested?  It seems very brief.

**Comment by Aniket21mathur** [comment]
Thanks.Reviewed.Tested. Although it's brief but the activity is working fine after these changes.These changes are automatically made when 2to3 is used. @pro-panda  please confirm is there any other change that should be considered?

**Comment by anmol27katyani** [comment]
@quozl , feel free to test, if it fails please close this PR :)
Sorry, I'm not so active these days.

**Comment by quozl** [comment]
Now that I've reviewed the activity source code, I'm not willing to test, as the activity has no use case that I can figure out.

**Review by rhl-bthr — COMMENTED** [review]
Closing in favor of #13

**Pull request closed without merging**
